// <auto-generated />
using System;
using IStock.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IStock.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190821163811_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("IStock.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Cid");

                    b.Property<int>("GlobalId");

                    b.Property<bool>("IsActive");

                    b.Property<int>("MinInStock");

                    b.Property<DateTime>("OpenDate");

                    b.Property<double>("ProCost");

                    b.Property<double>("ProSell");

                    b.Property<string>("ProductName");

                    b.Property<int>("SupId");

                    b.Property<int>("TotalInStock");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
